[project]
name = "agent-memory-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dapr-ext-fastapi>=1.15.0",
    "fastapi[standard]>=0.115.12",
    "openai-agents>=0.0.9",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.26.0",
]
